title: ❛ ❜
logo: /images/2.png
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

## Contact

Let's connect! Feel free to reach out to me via email:

[![Email Me](https://img.shields.io/badge/Email-Me-D14836?style=for-the-badge&logo=gmail&logoColor=white)](mailto:your.email@example.com)



